datasets:
# === Dataset 1 ===
- input_path : "sh1_0002_0001.h5"
  output_path : "./outputs/a"
  fitting_model : "gaussian"
  aspect_ratio : 226/901

  roi_list:
    - name: Ara_111
      peak: 1.5
      half_width: 0.3
    - name: Ara_023
      peak: 18.7
      half_width: 0.25
  save_diagnostics: False                     
  diagnostic_point_index: 1000                
  save_interactive_scattering_plot: False     
  save_extra_clean_param_maps: False           

# === Dataset 1 ===
- input_path : "sh1_0002_0001.h5"
  output_path : "./outputs/b"
  fitting_model : "pseudo_voigt"
  aspect_ratio : 226/901

  roi_list:
    - name: Ara_111
      peak: 1.5
      half_width: 0.3
    # - name: Ara_023
    #   peak: 18.7
    #   half_width: 0.25
  save_diagnostics: False                     
  diagnostic_point_index: 1000                
  save_interactive_scattering_plot: False     
  save_extra_clean_param_maps: False   

# ==TEMPLATE FOR DATASET==
#   - input_path: "<path/to/input_file>.h5"           # Path to HDF5 input file
#     output_path: "<path/to/output_directory>"       # Directory to save results
#     fitting_model: "<gaussian | pseudo_voigt>"      # Choose fitting model
#     aspect_ratio: "<width>/<height>"                # e.g. "1001/301"
    
#     roi_list:
#       - name: "<ROI_label_1>"                       # Unique label for this ROI
#         peak: <center_q_value>                      # Central q-value of the peak
#         half_width: <half_range_q>                  # Half-width for ROI in q-space, ensure enough range (gaussian: half_width>0.135, pseudo_voigt: half_width>0.09)
#       # - name: "<ROI_label_2>"                     # You can add more ROIs
#       #   peak: <center_q_value>
#       #   half_width: <half_range_q>

  # save_diagnostics: <true | false>                     # Save detailed fit diagnostics for debugging
  # diagnostic_point_index: <mesh_index>                # Point index to use when diagnostics are enabled
  # save_interactive_scattering_plot: <true | false>     # Save interactive q / intensity plot (HTML)
  # save_extra_clean_param_maps: <true | false>           # Save additional param maps without labels/titles/colorbars


